### ISSUE TITLE
paperColor Blue categories is wrong!

### ISSUE THREAD

**Issue by nvdcmptr** [bfeher/BFPaperColors#1]
in BFPaperColor for exasmple paperColorBlue200 has RGB(175,191,255)
but in google material [color-palette](http://www.google.com/design/spec/style/color.html#color-color-palette) Blue200 has RGB(144,202,249)
why?

**Comment by nvdcmptr** [comment]
in [MaterialColor](https://github.com/Ka0sTie/MaterialColor) has correct value.
blue200 has #90caf9

**Comment by bfeher** [comment]
Hi @nvdcmptr! Thanks for bringing this to my attention. I checked and actually many of the colors are now incorrect. I suspect that google updated their color sheet and I didn't notice. I will update all the colors and release a new pod soon.

**Comment by bfeher** [comment]
I pushed version 1.4.10 which updated all colors to once again match google's spec (who knows when they'll change again...), as well as added a couple new utility functions.

Thanks again for pointing this out to me!

**Comment by nvdcmptr** [comment]
wow!  tnx
