### ISSUE TITLE
paperColorTextDarkHint 

### ISSUE THREAD

**Issue by nvdcmptr** [bfeher/BFPaperColors#3]
paperColorTextDarkHint  in https://www.google.com/design/spec/style/color.html#color-ui-color-application has 0.38 alpha but in UIColor+BFPaperColors.m has 0.26 alpha.
plz fix it. tnks.

**Comment by bfeher** [comment]
Hi @nvdcmptr !

I double checked and yes, the value is different. Google keeps quietly updating these so please let me know if you find any more discrepancies. Thanks!

I fixed the value and also pushed a new cocoapod version (1.7.2).

Thanks again.
